server:
  port: 9999

spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: msa-order-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka